id: IAC343C3E
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:12:49.588722+00:00
last_modified: 2022-12-14 18:12:49.588730+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2019-08-21T02:40:26.791Z'
  creationid: CM
  eft-text-id: UT22084-066-005
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_247-Distinguishing_Phenomena_and_What_Is_Meaningful-v1
bases:
  '4676':
    source_metadata: null
    order: 1
    base_file: 4676.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
